version: '2'
services:
  memcache:
    image: memcached
    volumes:
      - /etc/localtime:/etc/localtime:ro
  redis:
    image: redis
    volumes:
      - ./redis_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '6379:6379'
  tor:
    image: jess/tor-proxy
    volumes:
      - ./torrc.default:/etc/tor/torrc.default
    ports:
      - '9050:9050'
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - memcache
      - redis
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      HTTP_PORT: '8000'
      REDIS_URL: 'redis://redis:6379'
      DB_HOST: '192.168.1.3'
      MEMCACHE_URL: 'memcache'
      TOR_IP: 'tor'
      PAGER: 'more'
      TZ: 'Pacific/Auckland'
    volumes:
      - .:/app
    # Following is development configuration
    command: foreman start