version: '2'
services:
  memcache:
    image: memcached
    volumes:
      - /etc/localtime:/etc/localtime:ro
  redis:
    image: redis
    volumes:
      - ./redis_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '6379:6379'
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - memcache
      - redis
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      HTTP_PORT: '8000'
      REDIS_URL: 'redis://redis:6379'
      DB_HOST: '192.168.20.13'
      MEMCACHE_URL: 'memcache'
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    # Following is development configuration
    command: foreman start