countdown_fetcher:
  cron: "00 10 * * *"
  queue: countdown
  class: CountdownJob
  description: "Fetch prices from countdown"

countdown_finish:
  cron: "30 15 * * *"
  queue: countdown
  class: CountdownFinishJob
  description: "Finish fetch prices from countdown"

sitemap:
  cron: "00 13 * * *"
  queue: sitemap
  class: SitemapJob
  description: "Refresh Sitemap"
