# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0bb5c55a5ba0005e9ece00e67ed020efe207372d7eca0e0737dc9056586f6e7dc5b7c29b7d9b6487808b13eccab62a7e7a53244dfe7ac089345fba520aabd0e

test:
  secret_key_base: e8b20a5c27b5071c48167ceb1693d8750ce60707edf2777c4a47b007c77dd918bcbd30bda6e6702f9388c364941e8b804de39ed86851928b08e12b9565f1dfbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 10e0d5aa11fb6d6f7e9abbbc9270390d1b4a322b7a0e7e870d2ce27d1385b5124cba5af53c2e98b39c8338dbcce6c9acd138affd958cde44705cf84192e733e6

dokku:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
